### ISSUE TITLE
syntax error near unexpected token

### ISSUE THREAD

**Issue by vamsiuppala** [chiphuyen/lazynlp#2]
I see a "syntax error near unexpected token `sgp.urls,'" on submitting the following command:
lazynlp.download_pages(sgp.urls, text_docs, timeout = 30, default_skip = True, extensions = [], domains = [])

Is there something wrong I am doing? sgp.urls has all the URLs, text_docs is the name of the folder to get the outputs into, the rest of the parameters as default.

**Comment by chiphuyen** [comment]
shouldn't sgp.urls and text_docs be in quotations, as in 'sgp.urls' and 'text_docs'?

**Comment by vamsiuppala** [comment]
I see the same issue nevertheless - should the command be run in a specific location or any location is fine as long as the right files and folders are pointed to?
Here's a screenshot of the errors I see -
<img width="1417" alt="screen shot 2019-03-02 at 9 44 38 am" src="https://user-images.githubusercontent.com/7885339/53683545-01a58680-3cd0-11e9-8ec4-7bb944bed22a.png">
