### ISSUE TITLE
Sum of n-gram counts

### ISSUE THREAD

**Issue by MichaMucha** [chiphuyen/lazynlp#8]
Thanks for building this, really nice work!

I was reading through the code and noticed this line
https://github.com/chiphuyen/lazynlp/blob/08696976ff1b521103147e51a187e23504fe23bd/lazynlp/analytics.py#L56
Were you looking to iteratively add up the line-ngram-counts? If yes, I can help complete that and raise a PR

Lmk

All the best

**Comment by chiphuyen** [comment]
I fixed this. Thank you for bringing it up!
