### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mrkafk** [chiphuyen/lazynlp#9]
Hello, 

There are legal problems with code with no license, where I work using code that has no license attached to it is outright banned. 

Would you be so kind to add some sort of license in a file? 

It would be very nice of you if it were something permissive, like MIT or Apache 2 or BSD too. 

Thank you!

**Comment by chiphuyen** [comment]
Oops my bad. It's MIT license now.

**Comment by mrkafk** [comment]
Thank you very much!
